#!/usr/bin/env bash
# test-mcp-w4.sh -- Tests for Wave 4 MCP Governance Layer.
# AUTO-GENERATED by gen-mcp-w4-test.sh -- do not edit directly.
#
# Tests: E1 tool identification, E2 SQL validation, E3 capability filtering,
#        E4 rate limiting, Integration signals
#
# Usage: bash tests/test-mcp-w4.sh
#
# @decision DEC-MCP-TEST-001
# @title End-to-end hook integration testing for pre-mcp.sh
# @status accepted
# @rationale Tests pipe JSON fixtures to pre-mcp.sh and verify JSON output.
#   Validates full stack: stdin parsing, jq extraction, risk classification,
#   capability filtering, deny/allow decisions. Pattern follows test-db-safety-w2a.sh.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
HOOKS_DIR="$(dirname "$SCRIPT_DIR")/hooks"
PRE_MCP_HOOK="$HOOKS_DIR/pre-mcp.sh"

_T_PASSED=0; _T_FAILED=0; _T_FAIL_DETAILS=""

pass() { echo "  PASS: $1"; _T_PASSED=$((_T_PASSED + 1)); }
fail() { echo "  FAIL: $1 -- $2"; _T_FAILED=$((_T_FAILED + 1)); _T_FAIL_DETAILS="${_T_FAIL_DETAILS}${1}: ${2}; "; }
assert_eq() {
    local n="$1" e="$2" a="$3"
    if [[ "$a" == "$e" ]]; then pass "$n"; else fail "$n" "expected '$e' got '$a'"; fi
}
assert_contains() {
    local n="$1" needle="$2" h="$3"
    if echo "$h" | grep -qF "$needle"; then pass "$n"; else fail "$n" "expected '$needle' in: $h"; fi
}
run_hook_json() {
    local tn="$1" tj="$2" hi
    hi=$(printf '{"tool_name":"%s","tool_input":%s}' "$tn" "$tj")
    printf '%s\n' "$hi" | bash "$PRE_MCP_HOOK" 2>/dev/null || true
}
get_decision() { echo "$1" | jq -r '.hookSpecificOutput.permissionDecision // empty' 2>/dev/null || true; }
get_reason()   { echo "$1" | jq -r '.hookSpecificOutput.permissionDecisionReason // empty' 2>/dev/null || true; }

echo ""; echo "=== Wave 4 MCP Governance Tests ==="; echo ""
if [[ ! -f "$PRE_MCP_HOOK" ]]; then
    echo "  FAIL: pre-mcp.sh not found at $PRE_MCP_HOOK"
    echo "Results: 0 passed, 1 failed, 1 total"; exit 1
fi

echo "--- E1: Database tool identification ---"
_O=$(run_hook_json "mcp__postgres__execute_query" '{"query":"SELECT 1"}'); assert_eq "E1.T01: postgres execute_query safe" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgresql__list_tables" '{}'); assert_eq "E1.T02: postgresql list_tables" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__mysql__execute_query" '{"query":"SELECT 1"}'); assert_eq "E1.T03: mysql execute_query" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__mariadb__run_query" '{"query":"SELECT 1"}'); assert_eq "E1.T04: mariadb run_query" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__sqlite__execute_query" '{"query":"SELECT 1"}'); assert_eq "E1.T05: sqlite execute_query" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__mongodb__run_query" '{"query":"db.find()"}'); assert_eq "E1.T06: mongodb run_query" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__mongo__find" '{}'); assert_eq "E1.T07: mongo find" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__redis__execute_command" '{"command":"GET k"}'); assert_eq "E1.T08: redis execute_command" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__cockroachdb__execute_sql" '{"sql":"SELECT 1"}'); assert_eq "E1.T09: cockroachdb execute_sql generic" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__fetch__fetch" '{"url":"https://example.com"}'); assert_eq "E1.T10: fetch non-db -> allow" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__context7__query-docs" '{"query":"bash"}'); assert_eq "E1.T11: context7 non-db -> allow" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__playwright__browser_navigate" '{"url":"https://x"}'); assert_eq "E1.T12: playwright non-db -> allow" "" "$(get_decision "$_O")"
echo ""

echo "--- E2: SQL argument validation ---"
# SQL stored in variables assembled from parts
_D_TRUNC_Q='{"query":"TRUNCATE TABLE orders"}'
_D_TRUNC_S='{"sql":"TRUNCATE TABLE orders"}'
_D_DEL_STMT='{"statement":"DELETE FROM users WHERE 1=1"}'
_D_INJECT='{"query":"SELECT 1; TRUNCATE TABLE users"}'
_D_CVE='{"query":"COMMIT; DROP SCHEMA public CASCADE"}'
_D_DEL_NW='{"query":"DELETE FROM sessions"}'
_D_TRUNC_U='{"query":"TRUNCATE TABLE users"}'
_D_TRUNC_L='{"sql":"TRUNCATE TABLE logs"}'
_D_CREATE='{"sql":"CREATE TABLE t (id INT)"}'
_D_ALTER='{"sql":"ALTER TABLE users ADD COLUMN x INT"}'
_O=$(run_hook_json "mcp__postgres__execute_query" "$_D_TRUNC_Q"); assert_eq "E2.T01: TRUNCATE query -> deny" "deny" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__execute_query" "$_D_TRUNC_S"); assert_eq "E2.T02: TRUNCATE sql field -> deny" "deny" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__execute_query" "$_D_DEL_STMT"); assert_eq "E2.T03: DELETE statement -> deny" "deny" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__execute_query" '{"query":"SELECT * FROM t WHERE id=1"}'); assert_eq "E2.T04: SELECT safe -> allow" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__execute_query" "$_D_INJECT"); assert_eq "E2.T05: injection TRUNCATE -> deny" "deny" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__execute_query" "$_D_CVE"); assert_eq "E2.T06: CVE-2025-53109 -> deny" "deny" "$(get_decision "$_O")"
_R=$(get_reason "$_O"); assert_contains "E2.T06b: reason has CVE" "CVE-2025-53109" "$_R"
_O=$(run_hook_json "mcp__postgres__execute_query" "$_D_DEL_NW"); assert_eq "E2.T07: DELETE no WHERE -> deny" "deny" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__list_tables" '{"schema":"public"}'); assert_eq "E2.T08: no SQL field -> allow" "" "$(get_decision "$_O")"
echo ""

echo "--- E3: Per-tool capability filtering ---"
_O=$(run_hook_json "mcp__postgres__list_tables" '{}'); assert_eq "E3.T01: list_tables read-only -> allow" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__describe_table" '{"table":"users"}'); assert_eq "E3.T02: describe_table read-only -> allow" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__get_schema" '{}'); assert_eq "E3.T03: get_schema read-only -> allow" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__list_schemas" '{}'); assert_eq "E3.T03b: list_schemas read-only -> allow" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__create_table" "$_D_CREATE"); assert_eq "E3.T04: create_table DDL -> deny" "deny" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__execute_ddl" "$_D_CREATE"); assert_eq "E3.T04b: execute_ddl DDL -> deny" "deny" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__alter_table" "$_D_ALTER"); assert_eq "E3.T05: alter_table DDL -> deny" "deny" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__drop_database" '{"database":"prod"}'); assert_eq "E3.T06: drop_database admin -> deny" "deny" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__grant" '{"privilege":"ALL"}'); assert_eq "E3.T07: grant admin -> deny" "deny" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__revoke" '{"privilege":"ALL"}'); assert_eq "E3.T08: revoke admin -> deny" "deny" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__create_database" '{"name":"newdb"}'); assert_eq "E3.T08b: create_database admin -> deny" "deny" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__execute_query" '{"query":"INSERT INTO logs VALUES (1)"}'); assert_eq "E3.T09: execute_query safe INSERT -> allow" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__custom_operation" '{"query":"SELECT 1"}'); assert_eq "E3.T10: unknown suffix safe SQL -> allow" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__custom_operation" "$_D_TRUNC_L"); assert_eq "E3.T11: unknown suffix TRUNCATE -> deny" "deny" "$(get_decision "$_O")"
echo ""

echo "--- E4: Rate limiting ---"
_RS="${CLAUDE_DIR:-$HOME/.claude}/.mcp-rate-state"
_RB=""; [[ -f "$_RS" ]] && _RB=$(cat "$_RS" 2>/dev/null || true)
_O=$(run_hook_json "mcp__postgres__execute_query" '{"query":"SELECT 1"}'); assert_eq "E4.T01: under rate limit -> no deny" "" "$(get_decision "$_O")"
_O=$(run_hook_json "mcp__postgres__list_tables" '{}'); assert_eq "E4.T02: read-only exempt -> allow" "" "$(get_decision "$_O")"
[[ -n "$_RB" ]] && printf '%s\n' "$_RB" > "$_RS"
echo ""

echo "--- Integration: signals and fail-closed ---"
_O=$(run_hook_json "mcp__postgres__execute_query" "$_D_TRUNC_U")
_R=$(get_reason "$_O"); assert_contains "Integration.T01: DB-GUARDIAN-REQUIRED in SQL deny" "DB-GUARDIAN-REQUIRED" "$_R"
_O=$(run_hook_json "mcp__postgres__drop_table" '{"table":"users"}')
_R=$(get_reason "$_O"); assert_contains "Integration.T02: DDL deny emits DB-GUARDIAN-REQUIRED" "DB-GUARDIAN-REQUIRED" "$_R"
printf '' | bash "$PRE_MCP_HOOK" 2>/dev/null || true; pass "Integration.T03: empty stdin no crash"
_SO=$(HOOK_GATE_SCAN=1 bash "$PRE_MCP_HOOK" < /dev/null 2>/dev/null); _SE=$?
assert_eq "Integration.T04: HOOK_GATE_SCAN exits 0" "0" "$_SE"
assert_contains "Integration.T05: HOOK_GATE_SCAN emits mcp-db-tool-identify" "mcp-db-tool-identify" "$_SO"
echo ""

_T_TOTAL=$((_T_PASSED + _T_FAILED))
echo "Results: ${_T_PASSED} passed, ${_T_FAILED} failed, ${_T_TOTAL} total"
[[ -n "$_T_FAIL_DETAILS" ]] && echo "Failures: ${_T_FAIL_DETAILS}"
[[ "$_T_FAILED" -gt 0 ]] && exit 1 || exit 0
